# Generated by Django 2.2 on 2019-04-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
                ('nickname', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
    ]
